version: '3.8'

services:
  db:
    image: mariadb:10.5
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_DATABASE: smsd
      MYSQL_USER: smsd
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root

  gammu:
    build: .
    volumes:
      - "./conf/smsdrc-user:/app/smsdrc-user"
    depends_on:
      - db
    environment:
      DB_DB: smsd
      DB_USER: smsd
      DB_PASS: password
      DB_HOST: db
    devices:
      - "${NAME_DEVICE_1}:/dev/mobile0"
      #- "${NAME_DEVICE_2}:/dev/mobile1"
    # environment:
      - TELEGRAM_BOT_TOKEN_1: xyz
      - TELEGRAM_CHAT_ID_1: xyz
      - MESSAGE_THREAD_ID_1: xyz
    #   - PIN1: 1234

